### ISSUE TITLE
Branch 3.2 crashes the game

### ISSUE THREAD

**Issue by panoskj** [tobystrong/CompactStorage#61]
I thought I'd try out the new branch but got an exception:

```
[10:23:16] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CompactStorage (compactstorage)

Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[up, north, south, west, east]} to down on block ic2:dynamite, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235) ~[awu$a.class:?]
	at ic2.core.block.BlockDynamite.func_176203_a(BlockDynamite.java:113) ~[BlockDynamite.class:?]
	at com.tattyseal.compactstorage.CompactStorage.lambda$null$0(CompactStorage.java:219) ~[CompactStorage.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_181]
	at com.tattyseal.compactstorage.CompactStorage.lambda$serverStarting$2(CompactStorage.java:218) ~[CompactStorage.class:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_181]
	at com.google.common.collect.Maps$IteratorBasedAbstractMap.forEachEntry(Maps.java:3661) ~[guava-21.0.jar:?]
	at com.google.common.collect.Maps$IteratorBasedAbstractMap$1.forEach(Maps.java:3655) ~[guava-21.0.jar:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[?:1.8.0_181]
	at com.tattyseal.compactstorage.CompactStorage.serverStarting(CompactStorage.java:208) ~[CompactStorage.class:?]

...
```

I haven't looked at why it happens yet, I'll let you know if I do.

**Comment by tobystrong** [comment]
Why are you trying the new branch it's not even released lol
